me:
  name: Solal Pirelli
  github: solalpirelli
  linkedin: solalpirelli
  summary: |-
     I currently work at [Sonar](https://sonarsource.com) on static code analysis to help developers find potential bugs and keep their code clean.

     I did my PhD at [EPFL](https://epfl.ch) on automated software verification, making it more practical for [real-world code](/research/klint)
     and showeing that verifiability helps [performance](/research/tinynf) and [safety](/research/tinynf-langs).  
     I also co-taught the [Software Engineering](https://github.com/sweng-epfl/public)
     and [Software Development Project](https://github.com/sweng-epfl/public/tree/main/project) courses.

     I also spend some of my free time on reproducibility and fraud detection in science, as you can see in my blog below.

# Without this Jekyll will not output posts with a future date
future: true

# Boilerplate for collections and their associated pages
collections:
  research:
    output: true
    permalink: /:collection/:path/
  guides:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: research
    values:
      layout: research

# Boilerplate for redirect support
plugins:
  - jekyll-redirect-from
