# Basic site info
locale: "en"
title: "Solal Pirelli's blog"
name: "Solal Pirelli"
url: "https://solalpirelli.github.io"
repository: "SolalPirelli/solalpirelli.github.io"
twitter:
  username: SolalPirelli  

# Boilerplate for collections and their associated pages
include: ["_pages"]
collections:
  publications:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: true
      share: false
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
      sidebar:
        - title: "Publications"
          text: "[&#8592; Back](../)"

# Boilerplate for the theme
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
