me:
  name: Solal Pirelli
  github: solalpirelli
  linkedin: solalpirelli
  contact_url: https://people.epfl.ch/solal.pirelli
  summary: |-
     I co-taught EPFL's [Software Engineering](https://github.com/sweng-epfl/public) course,
     and the associated [Software Development Project](https://github.com/sweng-epfl/public/tree/main/project) course.

     I research automated verification of software, making it more practical for [real-world code](/research/klint)
     and showing that verifiability is synonymous with [performance](/research/tinynf) and [safety](/research/tinynf-langs).

     I also work on reproducibility and fraud detection in science, as you can see in my blog below.

# Without this Jekyll will not output posts with a future date
future: true

# Boilerplate for collections and their associated pages
collections:
  research:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: research
    values:
      layout: research
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Boilerplate for redirect support
plugins:
  - jekyll-redirect-from
